# Generated by Django 4.2.5 on 2023-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_products_availablility'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='details',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
