# Generated by Django 4.2.5 on 2023-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_products_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
