# Generated by Django 4.2.5 on 2023-09-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
