# Generated by Django 4.2.5 on 2023-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_remove_wishlist_id_wishlist_wishlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
