# Generated by Django 4.2.5 on 2023-09-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_wishlist_wishlist_id_wishlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_n',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
