# Generated by Django 4.2.5 on 2023-09-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_brands_products_wishlist_customuser'),
        ('customer', '0019_alter_wishlist_user'),
    ]

    operations = [
    ]
