# Generated by Django 4.2.5 on 2023-09-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_merge_20230913_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
