# Generated by Django 4.2.5 on 2023-09-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_brands_products_customuser'),
        ('customer', '0021_delete_wishlist'),
    ]

    operations = [
    ]
